### PR TITLE
Fix Dockerfile issues with nodejs

### LINKED ISSUE #27: Example notebooks does not show widgets
The notebooks currently show:
```
Error displaying widget: model not found
```
when running `docker run -p 8878:8878 ipyvtk_simple jupyter lab --port=8878 --no-browser --ip=0.0.0.0 --allow-root` (using the updated Dockerfile from #26).

### PR DESCRIPTION
**Pull request by banesullivan**
Close #26: @jorgensd I am going to use this to supersede your changes so that conda is entirely managing the environment

I will also work to resolve #27 here

### CODE REVIEW

**Comment by banesullivan** [comment]
@martinRenou, apologies for the ping but I cannot figure out how to enable ipycanvas to resolve the `Error displaying widget: model not found` issue (in jupyterlab)

Do you have any insight on if there is something I am forgetting in the setup/installation in this Dockerfile?

```py
from ipycanvas import Canvas

canvas = Canvas(width=200, height=200)
canvas
```

Screen Shot 2021-02-05 at 9 38 35 AM

**Comment by martinRenou** [comment]
No worries. Is this JupyterLab? Which version is it?

Also, do you see errors in the JavaScript console?

`jupyter labextension list` might give us some helpful information.

**Comment by banesullivan** [comment]
It is JupyterLab and on version 3.0.7

`jupyter labextension list` shows:

```
root@dc4c3811775e:~/ipyvtk_simple# jupyter labextension list
JupyterLab v3.0.7
/opt/conda/share/jupyter/labextensions
        ipycanvas v0.8.2 enabled OK
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: /opt/conda/share/jupyter/lab
        ipyevents v1.8.1 enabled OK
```

Ahh, I'm seeing quite a few errors in the JS console. Notably: `index.es6.js:282 Plugin 'ipycanvas:plugin' failed to activate.` and `Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.` and `Error: Module ipycanvas, semver range ^0.8.2 is not registered as a widget module`

<details>

```
Some messages have been moved to the Issues panel.
index.es6.js:282 Plugin 'ipyevents' failed to activate.
(anonymous) @ index.es6.js:282
Promise.catch (async)
(anonymous) @ index.es6.js:281
e.start @ index.es6.js:280
Y @ index.out.js:625
async function (async)
Y @ index.out.js:181
load (async)
e @ bootstrap.js:115
async function (async)
e @ bootstrap.js:96
37559 @ bootstrap.js:85
r @ bootstrap:18
(anonymous) @ startup:6
(anonymous) @ main.7116e063a6536285205f.js:1
index.es6.js:283 Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.
    at W.e.resolveRequiredService (index.es6.js:197)
    at index.es6.js:155
    at Array.map (<anonymous>)
    at W.e.activatePlugin (index.es6.js:155)
    at index.es6.js:281
    at Array.map (<anonymous>)
    at W.e.start (index.es6.js:280)
    at Y (index.out.js:625)
(anonymous) @ index.es6.js:283
Promise.catch (async)
(anonymous) @ index.es6.js:281
e.start @ index.es6.js:280
Y @ index.out.js:625
async function (async)
Y @ index.out.js:181
load (async)
e @ bootstrap.js:115
async function (async)
e @ bootstrap.js:96
37559 @ bootstrap.js:85
r @ bootstrap:18
(anonymous) @ startup:6
(anonymous) @ main.7116e063a6536285205f.js:1
index.es6.js:282 Plugin 'ipycanvas:plugin' failed to activate.
(anonymous) @ index.es6.js:282
Promise.catch (async)
(anonymous) @ index.es6.js:281
e.start @ index.es6.js:280
Y @ index.out.js:625
async function (async)
Y @ index.out.js:181
load (async)
e @ bootstrap.js:115
async function (async)
e @ bootstrap.js:96
37559 @ bootstrap.js:85
r @ bootstrap:18
(anonymous) @ startup:6
(anonymous) @ main.7116e063a6536285205f.js:1
index.es6.js:283 Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.
    at W.e.resolveRequiredService (index.es6.js:197)
    at index.es6.js:155
    at Array.map (<anonymous>)
    at W.e.activatePlugin (index.es6.js:155)
    at index.es6.js:281
    at Array.map (<anonymous>)
    at W.e.start (index.es6.js:280)
    at Y (index.out.js:625)
(anonymous) @ index.es6.js:283
Promise.catch (async)
(anonymous) @ index.es6.js:281
e.start @ index.es6.js:280
Y @ index.out.js:625
async function (async)
Y @ index.out.js:181
load (async)
e @ bootstrap.js:115
async function (async)
e @ bootstrap.js:96
37559 @ bootstrap.js:85
r @ bootstrap:18
(anonymous) @ startup:6
(anonymous) @ main.7116e063a6536285205f.js:1
manager-base.js:274 Could not instantiate widget
(anonymous) @ manager-base.js:274
l @ manager-base.js:45
(anonymous) @ manager-base.js:26
a @ manager-base.js:18
Promise.then (async)
l @ manager-base.js:19
(anonymous) @ manager-base.js:20
A @ manager-base.js:16
e._make_model @ manager-base.js:258
(anonymous) @ manager-base.js:247
l @ manager-base.js:45
(anonymous) @ manager-base.js:26
(anonymous) @ manager-base.js:20
A @ manager-base.js:16
e.new_model @ manager-base.js:233
e.handle_comm_open @ manager-base.js:145
_handleCommOpen @ 523.fa256ee012d38a89b65a.js:1
_handleCommOpen @ default.js:1021
async function (async)
_handleCommOpen @ default.js:1020
_handleMessage @ default.js:1189
async function (async)
_handleMessage @ default.js:1151
(anonymous) @ default.js:109
Promise.then (async)
C._onWSMessage @ default.js:106
utils.js:119 Error: Could not create a model.
    at n (utils.js:119)
    at async _handleCommOpen (523.fa256ee012d38a89b65a.js:1)
    at async C._handleCommOpen (default.js:1020)
    at async C._handleMessage (default.js:1188)
n @ utils.js:119
Promise.catch (async)
e.handle_comm_open @ manager-base.js:150
_handleCommOpen @ 523.fa256ee012d38a89b65a.js:1
_handleCommOpen @ default.js:1021
async function (async)
_handleCommOpen @ default.js:1020
_handleMessage @ default.js:1189
async function (async)
_handleMessage @ default.js:1151
(anonymous) @ default.js:109
Promise.then (async)
C._onWSMessage @ default.js:106
default.js:1027 Exception opening new comm
_handleCommOpen @ default.js:1027
async function (async)
_handleCommOpen @ default.js:1020
_handleMessage @ default.js:1189
async function (async)
_handleMessage @ default.js:1151
(anonymous) @ default.js:109
Promise.then (async)
C._onWSMessage @ default.js:106
523.fa256ee012d38a89b65a.js:1 Uncaught (in promise) Error: Module ipycanvas, semver range ^0.8.2 is not registered as a widget module
    at x.loadClass (523.fa256ee012d38a89b65a.js:1)
    at x.<anonymous> (manager-base.js:264)
    at l (manager-base.js:45)
    at Object.next (manager-base.js:26)
    at manager-base.js:20
    at new Promise (<anonymous>)
    at A (manager-base.js:16)
    at x.e._make_model (manager-base.js:258)
    at x.<anonymous> (manager-base.js:247)
    at l (manager-base.js:45)
loadClass @ 523.fa256ee012d38a89b65a.js:1
(anonymous) @ manager-base.js:264
l @ manager-base.js:45
(anonymous) @ manager-base.js:26
(anonymous) @ manager-base.js:20
A @ manager-base.js:16
e._make_model @ manager-base.js:258
(anonymous) @ manager-base.js:247
l @ manager-base.js:45
(anonymous) @ manager-base.js:26
(anonymous) @ manager-base.js:20
A @ manager-base.js:16
e.new_model @ manager-base.js:233
e.handle_comm_open @ manager-base.js:145
_handleCommOpen @ 523.fa256ee012d38a89b65a.js:1
_handleCommOpen @ default.js:1021
Promise.then (async)
e.register_model @ manager-base.js:209
register_model @ 523.fa256ee012d38a89b65a.js:1
(anonymous) @ manager-base.js:249
l @ manager-base.js:45
(anonymous) @ manager-base.js:26
(anonymous) @ manager-base.js:20
A @ manager-base.js:16
e.new_model @ manager-base.js:233
e.handle_comm_open @ manager-base.js:145
_handleCommOpen @ 523.fa256ee012d38a89b65a.js:1
_handleCommOpen @ default.js:1021
async function (async)
_handleCommOpen @ default.js:1020
_handleMessage @ default.js:1189
async function (async)
_handleMessage @ default.js:1151
(anonymous) @ default.js:109
Promise.then (async)
C._onWSMessage @ default.js:106
523.fa256ee012d38a89b65a.js:1 Uncaught (in promise) Error: Module ipycanvas, semver range ^0.8.2 is not registered as a widget module
    at x.loadClass (523.fa256ee012d38a89b65a.js:1)
    at x.<anonymous> (manager-base.js:264)
    at l (manager-base.js:45)
    at Object.next (manager-base.js:26)
    at manager-base.js:20
    at new Promise (<anonymous>)
    at A (manager-base.js:16)
    at x.e._make_model (manager-base.js:258)
    at x.<anonymous> (manager-base.js:247)
    at l (manager-base.js:45)
loadClass @ 523.fa256ee012d38a89b65a.js:1
(anonymous) @ manager-base.js:264
l @ manager-base.js:45
(anonymous) @ manager-base.js:26
(anonymous) @ manager-base.js:20
A @ manager-base.js:16
e._make_model @ manager-base.js:258
(anonymous) @ manager-base.js:247
l @ manager-base.js:45
(anonymous) @ manager-base.js:26
(anonymous) @ manager-base.js:20
A @ manager-base.js:16
e.new_model @ manager-base.js:233
e.handle_comm_open @ manager-base.js:145
_handleCommOpen @ 523.fa256ee012d38a89b65a.js:1
_handleCommOpen @ default.js:1021
Promise.then (async)
register_model @ 523.fa256ee012d38a89b65a.js:1
(anonymous) @ manager-base.js:249
l @ manager-base.js:45
(anonymous) @ manager-base.js:26
(anonymous) @ manager-base.js:20
A @ manager-base.js:16
e.new_model @ manager-base.js:233
e.handle_comm_open @ manager-base.js:145
_handleCommOpen @ 523.fa256ee012d38a89b65a.js:1
_handleCommOpen @ default.js:1021
async function (async)
_handleCommOpen @ default.js:1020
_handleMessage @ default.js:1189
async function (async)
_handleMessage @ default.js:1151
(anonymous) @ default.js:109
Promise.then (async)
C._onWSMessage @ default.js:106
manager-base.js:274 Could not instantiate widget
(anonymous) @ manager-base.js:274
l @ manager-base.js:45
(anonymous) @ manager-base.js:26
a @ manager-base.js:18
Promise.then (async)
l @ manager-base.js:19
(anonymous) @ manager-base.js:20
A @ manager-base.js:16
e._make_model @ manager-base.js:258
(anonymous) @ manager-base.js:247
l @ manager-base.js:45
(anonymous) @ manager-base.js:26
(anonymous) @ manager-base.js:20
A @ manager-base.js:16
e.new_model @ manager-base.js:233
e.handle_comm_open @ manager-base.js:145
_handleCommOpen @ 523.fa256ee012d38a89b65a.js:1
_handleCommOpen @ default.js:1021
async function (async)
_handleCommOpen @ default.js:1020
_handleMessage @ default.js:1189
async function (async)
_handleMessage @ default.js:1151
(anonymous) @ default.js:109
Promise.then (async)
C._onWSMessage @ default.js:106
utils.js:119 Error: Could not create a model.
    at n (utils.js:119)
    at async _handleCommOpen (523.fa256ee012d38a89b65a.js:1)
    at async C._handleCommOpen (default.js:1020)
    at async C._handleMessage (default.js:1188)
n @ utils.js:119
Promise.catch (async)
e.handle_comm_open @ manager-base.js:150
_handleCommOpen @ 523.fa256ee012d38a89b65a.js:1
_handleCommOpen @ default.js:1021
async function (async)
_handleCommOpen @ default.js:1020
_handleMessage @ default.js:1189
async function (async)
_handleMessage @ default.js:1151
(anonymous) @ default.js:109
Promise.then (async)
C._onWSMessage @ default.js:106
default.js:1027 Exception opening new comm
_handleCommOpen @ default.js:1027
async function (async)
_handleCommOpen @ default.js:1020
_handleMessage @ default.js:1189
async function (async)
_handleMessage @ default.js:1151
(anonymous) @ default.js:109
Promise.then (async)
C._onWSMessage @ default.js:106
523.fa256ee012d38a89b65a.js:1 Uncaught (in promise) Error: Module ipyevents, semver range 1.8.1 is not registered as a widget module
    at x.loadClass (523.fa256ee012d38a89b65a.js:1)
    at x.<anonymous> (manager-base.js:264)
    at l (manager-base.js:45)
    at Object.next (manager-base.js:26)
    at manager-base.js:20
    at new Promise (<anonymous>)
    at A (manager-base.js:16)
    at x.e._make_model (manager-base.js:258)
    at x.<anonymous> (manager-base.js:247)
    at l (manager-base.js:45)
loadClass @ 523.fa256ee012d38a89b65a.js:1
(anonymous) @ manager-base.js:264
l @ manager-base.js:45
(anonymous) @ manager-base.js:26
(anonymous) @ manager-base.js:20
A @ manager-base.js:16
e._make_model @ manager-base.js:258
(anonymous) @ manager-base.js:247
l @ manager-base.js:45
(anonymous) @ manager-base.js:26
(anonymous) @ manager-base.js:20
A @ manager-base.js:16
e.new_model @ manager-base.js:233
e.handle_comm_open @ manager-base.js:145
_handleCommOpen @ 523.fa256ee012d38a89b65a.js:1
_handleCommOpen @ default.js:1021
Promise.then (async)
e.register_model @ manager-base.js:209
register_model @ 523.fa256ee012d38a89b65a.js:1
(anonymous) @ manager-base.js:249
l @ manager-base.js:45
(anonymous) @ manager-base.js:26
(anonymous) @ manager-base.js:20
A @ manager-base.js:16
e.new_model @ manager-base.js:233
e.handle_comm_open @ manager-base.js:145
_handleCommOpen @ 523.fa256ee012d38a89b65a.js:1
_handleCommOpen @ default.js:1021
async function (async)
_handleCommOpen @ default.js:1020
_handleMessage @ default.js:1189
async function (async)
_handleMessage @ default.js:1151
(anonymous) @ default.js:109
Promise.then (async)
C._onWSMessage @ default.js:106
523.fa256ee012d38a89b65a.js:1 Uncaught (in promise) Error: Module ipyevents, semver range 1.8.1 is not registered as a widget module
    at x.loadClass (523.fa256ee012d38a89b65a.js:1)
    at x.<anonymous> (manager-base.js:264)
    at l (manager-base.js:45)
    at Object.next (manager-base.js:26)
    at manager-base.js:20
    at new Promise (<anonymous>)
    at A (manager-base.js:16)
    at x.e._make_model (manager-base.js:258)
    at x.<anonymous> (manager-base.js:247)
    at l (manager-base.js:45)
loadClass @ 523.fa256ee012d38a89b65a.js:1
(anonymous) @ manager-base.js:264
l @ manager-base.js:45
(anonymous) @ manager-base.js:26
(anonymous) @ manager-base.js:20
A @ manager-base.js:16
e._make_model @ manager-base.js:258
(anonymous) @ manager-base.js:247
l @ manager-base.js:45
(anonymous) @ manager-base.js:26
(anonymous) @ manager-base.js:20
A @ manager-base.js:16
e.new_model @ manager-base.js:233
e.handle_comm_open @ manager-base.js:145
_handleCommOpen @ 523.fa256ee012d38a89b65a.js:1
_handleCommOpen @ default.js:1021
Promise.then (async)
register_model @ 523.fa256ee012d38a89b65a.js:1
(anonymous) @ manager-base.js:249
l @ manager-base.js:45
(anonymous) @ manager-base.js:26
(anonymous) @ manager-base.js:20
A @ manager-base.js:16
e.new_model @ manager-base.js:233
e.handle_comm_open @ manager-base.js:145
_handleCommOpen @ 523.fa256ee012d38a89b65a.js:1
_handleCommOpen @ default.js:1021
async function (async)
_handleCommOpen @ default.js:1020
_handleMessage @ default.js:1189
async function (async)
_handleMessage @ default.js:1151
(anonymous) @ default.js:109
Promise.then (async)
C._onWSMessage @ default.js:106
523.fa256ee012d38a89b65a.js:1 Error: Module ipycanvas, semver range ^0.8.2 is not registered as a widget module
    at x.loadClass (523.fa256ee012d38a89b65a.js:1)
    at x.<anonymous> (manager-base.js:264)
    at l (manager-base.js:45)
    at Object.next (manager-base.js:26)
    at manager-base.js:20
    at new Promise (<anonymous>)
    at A (manager-base.js:16)
    at x.e._make_model (manager-base.js:258)
    at x.<anonymous> (manager-base.js:247)
    at l (manager-base.js:45)
renderModel @ 523.fa256ee012d38a89b65a.js:1
async function (async)
renderModel @ 523.fa256ee012d38a89b65a.js:1
createRenderedMimetype @ widget.js:435
createOutputItem @ widget.js:407
_insertOutput @ widget.js:390
onModelChanged @ widget.js:218
m @ index.es6.js:459
l @ index.es6.js:416
e.emit @ index.es6.js:99
_onListChanged @ model.js:231
m @ index.es6.js:459
l @ index.es6.js:416
e.emit @ index.es6.js:99
push @ observablelist.js:135
_add @ model.js:207
add @ model.js:128
_onIOPub @ widget.js:92
_handleIOPub @ future.js:229
async function (async)
_handleIOPub @ future.js:225
handleMsg @ future.js:199
_handleMessage @ default.js:1151
(anonymous) @ default.js:109
Promise.then (async)
C._onWSMessage @ default.js:106
```

</details>

**Comment by martinRenou** [comment]
Mmmh I wonder if the fact that you installed ipyevents is not the reason. ipyevents does not support JupyterLab 3 yet, it might pull an out-of-date widgets package.

I am planning on pushing a PR to ipyevents this week-end if I have time fixing JupyterLab 3 support.

**Comment by banesullivan** [comment]
Simply downgrading to JupyterLab 2 doesn't resolve the issue unfortunately:

```
root@34812990c8f1:~/ipyvtk_simple# jupyter labextension list
JupyterLab v2.0.0
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        ipycanvas v0.8.2  enabled  OK
        ipyevents v1.8.1  enabled  OK
```

I still get a lot of JS console errors for `...is not registered as a widget module`

**Comment by banesullivan** [comment]
It looks to me that everything is working on JupyterLab 3 now (likely the upstream dependencies were updated). I am going to merge this now.

**Comment by martinRenou** [comment]
I've pushed a PR to update ipyevents for JupyterLab 3 https://github.com/mwcraig/ipyevents/pull/66. You'll soon not need nodejs anymore and should be able to have everything working with just pip or conda.

**Comment by banesullivan** [comment]
That's seriously awesome to hear! I'll keep an eye on that and come back to these Dockerfiles when that's ready

**Pull request merged**
