### PR TITLE
Throttling from ipyevents

### PR DESCRIPTION
**Pull request by banesullivan**
Utilize https://github.com/mwcraig/ipyevents/pull/55

Adress #3 and follow up #8 

Todo: 

- [x] Specify the version of `ipyevents` when a release is made with these new features

### CODE REVIEW

**Comment by mwcraig** [comment]
I just released 0.8.0 which contains the throttling. You might want to give it a try locally before updating here. Thanks again for asking about throttling!

**Comment by banesullivan** [comment]
Working locally with the release on PyPI! Now we just need https://github.com/conda-forge/ipyevents-feedstock/pull/20

**Comment by banesullivan** [comment]
Thanks for such a quick implementation of this, @mwcraig!!

**Comment by banesullivan** [comment]
It's working on MyBinder: https://mybinder.org/v2/gh/Kitware/ipyvtk-simple/throttle-ipyevent

However, the status icon in the top right of the notebook goes wild anytime I hover the mouse over the canvas. Is this expected? See below

Otherwise, I think it is working okay... I'll add a way to set the time for the throttle so that it can be adjusted

**Comment by banesullivan** [comment]
Since this is generally working and we are deploying yet, I am going to merge to master to continue some other work

**Comment by mwcraig** [comment]
> However, the status icon in the top right of the notebook goes wild anytime I hover the mouse over the canvas. Is this expected? 

Yes -- it goes solid when the kernel is busy,in this case passing messages back and forth. Without throttling it is more or less solid gray.

> Working locally with the release on PyPI!

🎉 Wasn't 100% sure it would, tbh. I kept making git mistakes last night.

> Now we just need conda-forge/ipyevents-feedstock#20

Just merged, so should be able to `conda install` in ~1 hour

**Comment by banesullivan** [comment]
Awesome!! thanks so much @mwcraig!

**Pull request merged**
